name: 'Build Tika Container'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'curator-auth-77e8f'
  REGION: 'europe-west1'
  SERVICE: 'tika'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/730465313064/locations/global/workloadIdentityPools/github/providers/github-actions'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'ptah-611@curator-auth-77e8f.iam.gserviceaccount.com'

      - name: 'Docker Auth'
        uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/service:latest"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
